name: Build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: |
          3.10
          3.11
          3.12
          3.13
    - run: pip install build
    - run: python -m build
  pip-install:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: |
          3.10
          3.11
          3.12
          3.13
    - run: pip install build
    - run: pip install .
  pip-editable-install:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: |
          3.10
          3.11
          3.12
          3.13
    - run: pip install build
    - run: pip install -e .
